[package]
name = "onshape-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
hmac = "0.12"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
